// Code generated by hertz generator.

package user

import (
	"github.com/cloudwego/hertz/pkg/app"

	"github.com/2451965602/LMS/biz/router/auth"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteuserMw() []app.HandlerFunc {
	// your code...
	return append(make([]app.HandlerFunc, 0),
		auth.AccessTokenAuth(),
	)
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateuserMw() []app.HandlerFunc {
	// your code...
	return append(make([]app.HandlerFunc, 0),
		auth.AccessTokenAuth(),
	)
}

func _adminMw() []app.HandlerFunc {
	// your code...
	return append(make([]app.HandlerFunc, 0),
		auth.AccessTokenAuth(),
	)
}

func _admindeleteuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminupdateuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userinfoMw() []app.HandlerFunc {
	// your code...
	return append(make([]app.HandlerFunc, 0),
		auth.AccessTokenAuth(),
	)
}

func _refreshtokenMw() []app.HandlerFunc {
	// your code...
	return append(make([]app.HandlerFunc, 0),
		auth.RefreshTokenAuth(),
	)
}
