// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"

	"github.com/2451965602/LMS/biz/dal"
	mw "github.com/2451965602/LMS/biz/middleware"
	"github.com/2451965602/LMS/config"
)

func init() {
	config.Init()
	mw.Init()
	err := dal.Init()
	if err != nil {
		hlog.Errorf("dal.Init: %v", err)
		panic(err)
	}
}

func main() {
	h := server.Default()

	register(h)
	h.Spin()
}
