// Code generated by hertz generator.

package borrow

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _reserveMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _reserve0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _cancelreservationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getreservationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _bookMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _borrowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getborrowrecordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _renewMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _returnbookMw() []app.HandlerFunc {
	// your code...
	return nil
}
