// Code generated by hertz generator.

package book

import (
	"github.com/cloudwego/hertz/pkg/app"

	"github.com/2451965602/LMS/biz/router/auth"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return append(make([]app.HandlerFunc, 0),
		auth.AccessTokenAuth(),
	)
}

func _bookMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addbookMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletebookMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getbookMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatebookMw() []app.HandlerFunc {
	// your code...
	return nil
}
