// Code generated by hertz generator.

package borrow

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"

	borrow "github.com/2451965602/LMS/biz/model/borrow"
)

// Reserve .
// @router /reserve [POST]
func Reserve(ctx context.Context, c *app.RequestContext) {
	var err error
	var req borrow.ReservationRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(borrow.ReservationResponse)

	c.JSON(consts.StatusOK, resp)
}

// CancelReservation .
// @router /reserve/cancel [POST]
func CancelReservation(ctx context.Context, c *app.RequestContext) {
	var err error
	var req borrow.CancelReservationRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(borrow.CancelReservationResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetReservation .
// @router /reserve/record [GET]
func GetReservation(ctx context.Context, c *app.RequestContext) {
	var err error
	var req borrow.GetReservationRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(borrow.GetReservationResponse)

	c.JSON(consts.StatusOK, resp)
}
