// Code generated by hertz generator.

package user

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"

	user "github.com/2451965602/LMS/biz/model/user"
)

// AdminUpdateUser .
// @router /user/admin/update [PUT]
func AdminUpdateUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.AdminUpdateUserRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.AdminUpdateUserResponse)

	c.JSON(consts.StatusOK, resp)
}

// AdminDeleteUser .
// @router /user/admin/delete [DELETE]
func AdminDeleteUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.AdminDeleteUserRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.AdminDeleteUserResponse)

	c.JSON(consts.StatusOK, resp)
}
