// Code generated by hertz generator.

package user

import (
	"context"

	"github.com/2451965602/LMS/biz/pack"
	"github.com/2451965602/LMS/biz/service"

	"github.com/cloudwego/hertz/pkg/app"

	user "github.com/2451965602/LMS/biz/model/user"
)

// AdminUpdateUser .
// @router /user/admin/update [PUT]
func AdminUpdateUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.AdminUpdateUserRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp := new(user.AdminUpdateUserResponse)

	info, err := service.NewUserService(ctx, c).AdminUpdateUser(ctx, req)
	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp.Base = pack.BuildBaseResp(err)
	resp.Data = pack.BuildUserResp(info)
	pack.SendResponse(c, resp)
}

// AdminDeleteUser .
// @router /user/admin/delete [DELETE]
func AdminDeleteUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.AdminDeleteUserRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp := new(user.AdminDeleteUserResponse)

	err = service.NewUserService(ctx, c).AdminDeleteUser(ctx, req)
	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}
	resp.Base = pack.BuildBaseResp(err)
	pack.SendResponse(c, resp)
}
