// Code generated by hertz generator.

package booktype

import (
	"context"

	"github.com/2451965602/LMS/biz/pack"
	"github.com/2451965602/LMS/biz/service"

	"github.com/cloudwego/hertz/pkg/app"

	booktype "github.com/2451965602/LMS/biz/model/booktype"
)

// AddBookType .
// @router /booktype/add [POST]
func AddBookType(ctx context.Context, c *app.RequestContext) {
	var err error
	var req booktype.AddBookTypeRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp := new(booktype.AddBookTypeResponse)

	info, err := service.NewBookTypeService(ctx, c).AddBookType(ctx, req)
	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp.Base = pack.BuildBaseResp(nil)
	resp.Data = pack.BuildBookTypeResp(info)

	pack.SendResponse(c, resp)
}

// UpdateBookType .
// @router /booktype/update [PUT]
func UpdateBookType(ctx context.Context, c *app.RequestContext) {
	var err error
	var req booktype.UpdateBookTypeRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp := new(booktype.UpdateBookTypeResponse)

	info, err := service.NewBookTypeService(ctx, c).UpdateBookType(ctx, req)
	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp.Base = pack.BuildBaseResp(nil)
	resp.Data = pack.BuildBookTypeResp(info)

	pack.SendResponse(c, resp)
}

// DeleteBookType .
// @router /booktype/delete [DELETE]
func DeleteBookType(ctx context.Context, c *app.RequestContext) {
	var err error
	var req booktype.DeleteBookTypeRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp := new(booktype.DeleteBookTypeResponse)

	err = service.NewBookTypeService(ctx, c).DeleteBookType(ctx, req)
	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp.Base = pack.BuildBaseResp(nil)

	pack.SendResponse(c, resp)
}

// GetBookType .
// @router /booktype/get [GET]
func GetBookType(ctx context.Context, c *app.RequestContext) {
	var err error
	var req booktype.GetBookTypeRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp := new(booktype.GetBookTypeResponse)

	info, total, err := service.NewBookTypeService(ctx, c).SearchBookType(ctx, req)
	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp.Base = pack.BuildBaseResp(nil)
	resp.Data = pack.BuildBookTypeListResp(info)
	resp.Total = total

	pack.SendResponse(c, resp)
}
