// Code generated by hertz generator.

package booktype

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _booktypeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addbooktypeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletebooktypeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getbooktypeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatebooktypeMw() []app.HandlerFunc {
	// your code...
	return nil
}
