// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"

	book "github.com/2451965602/LMS/biz/router/book"
	booktype "github.com/2451965602/LMS/biz/router/booktype"
	borrow "github.com/2451965602/LMS/biz/router/borrow"
	model "github.com/2451965602/LMS/biz/router/model"
	user "github.com/2451965602/LMS/biz/router/user"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	booktype.Register(r)

	book.Register(r)

	borrow.Register(r)

	model.Register(r)

	user.Register(r)

}
