// Code generated by hertz generator.

package book

import (
	"context"

	"github.com/2451965602/LMS/biz/pack"
	"github.com/2451965602/LMS/biz/service"

	"github.com/cloudwego/hertz/pkg/app"

	book "github.com/2451965602/LMS/biz/model/book"
)

// AddBook .
// @router /book/add [POST]
func AddBook(ctx context.Context, c *app.RequestContext) {
	var err error
	var req book.AddBookRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp := new(book.AddBookResponse)

	id, err := service.NewBookService(ctx, c).AddBook(ctx, req)
	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp.Base = pack.BuildBaseResp(err)
	resp.BookID = id

	pack.SendResponse(c, resp)
}

// UpdateBook .
// @router /book/update [PUT]
func UpdateBook(ctx context.Context, c *app.RequestContext) {
	var err error
	var req book.UpdateBookRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp := new(book.UpdateBookResponse)

	info, err := service.NewBookService(ctx, c).UpdateBook(ctx, req)
	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp.Base = pack.BuildBaseResp(err)
	resp.Data = pack.BuildBookResp(info)

	pack.SendResponse(c, resp)
}

// DeleteBook .
// @router /book/delete [DELETE]
func DeleteBook(ctx context.Context, c *app.RequestContext) {
	var err error
	var req book.DeleteBookRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp := new(book.DeleteBookResponse)

	err = service.NewBookService(ctx, c).DeleteBook(ctx, req)
	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp.Base = pack.BuildBaseResp(err)

	pack.SendResponse(c, resp)
}

// GetBook .
// @router /book/get [GET]
func GetBook(ctx context.Context, c *app.RequestContext) {
	var err error
	var req book.GetBookRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp := new(book.GetBookResponse)

	info, total, err := service.NewBookService(ctx, c).SearchBook(ctx, req)
	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp.Base = pack.BuildBaseResp(err)
	resp.Data = pack.BuildBookListResp(info)
	resp.TotalCount = total

	pack.SendResponse(c, resp)
}
