name: Publish Go Binary

# 触发条件：在 push 到 main 分支后
on:
  push:
    branches:
      - main
env:
  GITHUB_TOKEN: ${{ secrets.GOACTION }}      
jobs:
  buildAndDeploy:
    runs-on:  ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # 交叉构建，多平台交叉编译
    strategy:
      matrix:
        include:
          - goarch: amd64
            goos: linux
          - goarch: amd64
            goos: darwin
          - goarch: arm64
            goos: linux
          - goarch: arm64
            goos: darwin
    # 使用checkout
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with: 
        go-version: '>=1.23.6'
    - run: go version
    - name: Build
      run: |
        cd LMS
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o LMS
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}            
    - name: Packaging...
      run: |
        mkdir LMS-${{ matrix.goos }}-${{ matrix.goarch }}
        mv LMS/LMS LMS-${{ matrix.goos }}-${{ matrix.goarch }}/LMS
        cp -r config LMS-${{ matrix.goos }}-${{ matrix.goarch }}/config
        tar czf LMS-${{ matrix.goos }}-${{ matrix.goarch }}.tgz LMS-${{ matrix.goos }}-${{ matrix.goarch }}
    - name: Save artifact
      uses: actions/upload-artifact@v3
      with:
        name: LMS-${{ matrix.goos }}-${{ matrix.goarch }}.tgz
        path: LMS-${{ matrix.goos }}-${{ matrix.goarch }}.tgz
